# Берём официальный образ Python
FROM python:3.9-slim

# Создаём папку /app внутри контейнера
WORKDIR /app

# Копируем файл с зависимостями
COPY requirements.txt .

# Устанавливаем зависимости
RUN pip install -r requirements.txt

# Копируем ВЕСЬ проект в контейнер
COPY . .

# Запускаем приложение при старте контейнера
CMD ["python", "app.py"]