name: Docker Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Загружаем код из репозитория
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Собираем Docker-образ
      - name: Build Docker image
        run: docker build -t my-flask-app .

      # 3. Запускаем контейнер и проверяем работу
      - name: Test Flask app
        run: |
          docker run -d -p 5000:5000 --name flask-container my-flask-app
          sleep 5  # Ждём запуска сервера
          curl http://localhost:5000  # Проверяем ответ
