name: Docker Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:

      - uses: actions/checkout@v4


      - name: Build Docker image
        run: |
          docker build --rm -t my-app .


      - name: Test Flask app
        run: |
          docker run -d --rm -p 5000:5000 --name flask-container my-app
          sleep 10  
          docker ps  
          curl -v http://localhost:5000 || echo "Тест не прошёл"
          docker logs flask-container